# Generated by Django 2.1 on 2019-01-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('player_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubInfo'),
            preserve_default=False,
        ),
    ]
