# Generated by Django 2.1 on 2019-01-30 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20190130_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMemberships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('description', models.TextField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubInfo')),
            ],
        ),
        migrations.AddField(
            model_name='pitch',
            name='rental',
            field=models.IntegerField(choices=[('0', 'Not Available To Rent'), ('1', 'Available To Rent')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='pitch',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
