# Generated by Django 2.1 on 2019-01-30 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20190130_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
