# Generated by Django 2.1 on 2019-01-30 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20190130_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='rental',
            field=models.IntegerField(choices=[('0', 'Not Available To Rent'), ('1', 'Available To Rent')], default=0),
        ),
    ]
