# Generated by Django 2.1 on 2019-01-30 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20190130_1722'),
    ]

    operations = [

        migrations.AddField(
            model_name='pitch',
            name='max_people',
            field=models.IntegerField(null=True),
        ),
    ]
