# Generated by Django 2.1 on 2019-02-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20190206_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='rental',
            field=models.CharField(choices=[('0', 'Not Available To Rent'), ('1', 'Available To Rent')], max_length=1),
        ),
    ]
