# Generated by Django 2.1.5 on 2019-05-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_auto_20190521_1426'),
        ('orders', '0002_order_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='club_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubInfo'),
            preserve_default=False,
        ),
    ]
