# Generated by Django 2.1 on 2019-02-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0008_auto_20190202_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('payment_type', models.CharField(choices=[('1', 'Card'), ('2', 'Cash')], max_length=1)),
                ('is_cancelled', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=1)),
                ('pitch_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='clubs.Pitch')),
                ('rental_cost', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.Pitch', to_field='rental_price')),
            ],
        ),
    ]
