# Generated by Django 2.1.5 on 2019-05-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapitch', '0003_auto_20190206_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpitch',
            name='is_cancelled',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Yes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='rentpitch',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('1', 'Card'), ('2', 'Cash')], max_length=1),
        ),
        migrations.AlterField(
            model_name='rentpitch',
            name='rental_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
