# Generated by Django 2.1.5 on 2019-05-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapitch', '0004_auto_20190522_2242'),
        ('rentapitch', '0004_auto_20190522_2128'),
    ]

    operations = [
    ]
