# Generated by Django 2.1.5 on 2019-05-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapitch', '0005_merge_20190527_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpitch',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='rentpitch',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='rentpitch',
            name='rental_cost',
        ),
    ]
