# Generated by Django 2.1 on 2019-01-30 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_register_package', models.IntegerField(default=0)),
                ('roster_package', models.IntegerField(default=0)),
                ('rent_a_pitch_package', models.IntegerField(default=0)),
                ('shop_package', models.IntegerField(default=0)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubInfo')),
            ],
        ),

    ]
