# Generated by Django 2.1 on 2019-02-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20190202_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='rental',
            field=models.CharField(choices=[('0', 'Not Available To Rent'), ('1', 'Available To Rent')], max_length=1),
        ),
    ]
