# Generated by Django 2.1 on 2019-02-03 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_clubposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpackages',
            name='player_register_expiry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='rent_a_pitch_expiry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='roster_expiry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='shop_expiry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
