# Generated by Django 2.1 on 2019-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_auto_20190203_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpackages',
            name='player_register_package',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Not Active')], max_length=1),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='rent_a_pitch_package',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Not Active')], max_length=1),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='roster_package',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Not Active')], max_length=1),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='shop_package',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Not Active')], max_length=1),
        ),
    ]
