# Generated by Django 2.1 on 2019-02-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20190203_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='rental',
            field=models.IntegerField(choices=[('0', 'Not Available To Rent'), ('1', 'Available To Rent')], max_length=1),
        ),
    ]
