# Generated by Django 2.1.5 on 2019-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_auto_20190210_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpackages',
            name='player_register_package',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Not Active')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='player_register_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='rent_a_pitch_package',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Not Active')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='rent_a_pitch_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='roster_package',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Not Active')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='roster_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='shop_package',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Not Active')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='clubpackages',
            name='shop_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
    ]
