# Generated by Django 2.1.5 on 2019-05-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_auto_20190429_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pitch_pics'),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, upload_to='team_pics'),
        ),
    ]
