# Generated by Django 2.1.5 on 2019-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_auto_20190521_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='description',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
