# Generated by Django 2.1.5 on 2019-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_auto_20190521_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubposts',
            name='photo',
            field=models.ImageField(blank=True, default=0, upload_to='club_post_pics'),
            preserve_default=False,
        ),
    ]
