# Generated by Django 2.1.5 on 2019-05-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_auto_20190521_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='paypal_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
