# Generated by Django 2.1 on 2019-01-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=8)),
                ('start_time', models.TimeField(default='')),
                ('finish_time', models.TimeField(default='')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubInfo')),
                ('pitch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Pitch')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Team')),
            ],
        ),
    ]
