# Generated by Django 2.1 on 2019-01-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20190130_1722'),
        ('player_register', '0002_player_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='membership_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubMemberships'),
            preserve_default=False,
        ),
    ]
