# Generated by Django 2.1.5 on 2019-05-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_register', '0004_player_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='price',
        ),
    ]
