# Generated by Django 2.1.5 on 2019-04-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterid',
            name='reoccuring_event',
            field=models.BooleanField(default=False),
        ),
    ]
