# Generated by Django 2.1.5 on 2019-05-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_rosterid_reoccuring_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterid',
            name='reoccuring_event',
            field=models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], max_length=1),
        ),
    ]
