# Generated by Django 2.1.5 on 2019-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_auto_20190520_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterid',
            name='reoccuring_day',
            field=models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rosterid',
            name='reoccuring_event',
            field=models.BooleanField(default=False),
        ),
    ]
