# Generated by Django 2.1.5 on 2019-05-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_auto_20190520_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterid',
            name='reoccuring_day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1),
        ),
    ]
