# Generated by Django 2.1 on 2019-02-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_clubposts'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='club_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='club_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('NA', 'One Size'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
